version: '2'
services:
    adidascityitinerary-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/adidascityitinerary/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=adidascityitinerary
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
